In [6]:
import pandas as pd
import json
from IPython.display import display

file_name = "2026-03-20_11-46-40"
with open(f"../data/raw/variant_16/{file_name}.json", "r", encoding="utf-8") as f:
    data = json.load(f)

features = data["features"]
df = pd.json_normalize(features)

records = []
for feature in data["features"]:
    props = feature["properties"]
    coords = feature["geometry"]["coordinates"]

    record = {
        "id" : str(feature["id"]),
        "time": pd.to_datetime(props["time"], unit="ms", errors="coerce"),
        "mag": float(props["mag"]),
        "place": str(props["place"]),
        "latitude": float(coords[1]),
        "longitude": float(coords[0]),
        "depth_km": float(coords[2]),
        "alert": str(props["alert"]),
        "tsunami": bool(props["tsunami"]),
        "sig": int(props["sig"]),
    }
    records.append(record)

df = pd.DataFrame(records)

display(df.head())
print("\n", df.dtypes)
print("\n", df.shape)
print("\n", df.columns)
print("/n", "Количество дубликатов по time:", df.duplicated(subset=["time"]).sum())

clean_df = df.drop_duplicates(subset=["time"], keep="first")
clean_df = clean_df.sort_values("time").reset_index(drop=True)

clean_df.to_csv(f"../data/normalized/variant_16/{file_name}.csv")
print("\n", "normalized данные сохранены")

display(clean_df.head(50))

,id,time,mag,place,latitude,longitude,depth_km,alert,tsunami,sig
0,us6000sh9j,2026-03-18 21:23:02.008,4.7,"52 km NE of Misawa, Japan",40.9524,141.9080,64.376,None,False,340
1,us6000sh54,2026-03-18 10:08:43.719,4.8,"Izu Islands, Japan region",32.4671,141.7638,10.000,None,False,355
2,us6000sh22,2026-03-17 23:39:22.117,4.3,"Izu Islands, Japan region",30.3452,137.4131,503.225,None,False,284
3,us6000sh1g,2026-03-17 21:13:32.230,4.5,"80 km S of Kushiro, Japan",42.2522,144.3656,35.000,None,False,312
4,us6000sgkn,2026-03-16 11:37:49.386,4.6,"37 km SE of Itō, Japan",34.7732,139.4133,121.973,None,False,326

 id                      str
time         datetime64[ms]
mag                 float64
place                   str
latitude            float64
longitude           float64
depth_km            float64
alert                   str
tsunami                bool
sig                   int64
dtype: object

 (47, 10)

 Index(['id', 'time', 'mag', 'place', 'latitude', 'longitude', 'depth_km',
       'alert', 'tsunami', 'sig'],
      dtype='str')
/n Количество дубликатов по time: 0

 normalized данные сохранены

,id,time,mag,place,latitude,longitude,depth_km,alert,tsunami,sig
0,us6000sa20,2026-02-18 22:40:28.752,4.6,"80 km E of Tomioka, Japan",37.3977,141.9228,43.546,None,False,326
1,us6000sa5d,2026-02-19 08:24:30.319,4.4,"11 km SW of Katsuura, Japan",35.0735,140.2253,10.000,None,False,298
2,us6000sadg,2026-02-20 10:39:18.090,4.5,"129 km ESE of Iwaki, Japan",36.6758,142.2563,10.000,None,False,312
3,us6000sae0,2026-02-20 14:16:30.267,5.3,"71 km ENE of Mutsu, Japan",41.5427,141.9999,54.152,None,False,432
4,us6000sai0,2026-02-20 18:59:32.395,4.2,"88 km SSE of Onagawa Chō, Japan",37.7788,142.0091,51.363,None,False,271
5,us6000samv,2026-02-21 17:09:06.318,4.3,"53 km NE of Misawa, Japan",40.9776,141.8946,65.940,None,False,284
6,us6000saxx,2026-02-23 02:59:33.402,4.6,"86 km ENE of Noda, Japan",40.4445,142.7401,52.286,None,False,326
7,us7000s2l1,2026-02-23 03:50:10.969,4.2,"94 km ENE of Noda, Japan",40.4307,142.8475,54.739,None,False,271
8,us7000rzvn,2026-02-23 22:34:21.130,4.5,"59 km SE of Shimoda, Japan",34.3291,139.4449,139.765,None,False,312
9,us7000rzvv,2026-02-23 23:03:41.033,4.8,"7 km E of Nanao, Japan",37.0384,137.0444,259.384,None,False,354
10,us7000s3ec,2026-02-24 04:27:01.348,4.0,"20 km SE of Onagawa Chō, Japan",38.2985,141.5933,69.181,None,False,246
11,us7000s3ek,2026-02-24 11:48:00.836,4.4,"Izu Islands, Japan region",30.4352,140.2591,10.000,None,False,298
12,us7000s01b,2026-02-24 18:16:41.527,4.6,"7 km SSE of Miyako, Japan",39.5816,141.9738,61.812,None,False,326
13,us7000s066,2026-02-25 09:07:45.997,5.2,"96 km S of Sukumo, Japan",32.0687,132.5883,17.334,None,False,416
14,us7000s069,2026-02-25 09:41:35.742,4.6,"68 km ENE of Mutsu, Japan",41.4720,142.0029,65.674,None,False,326
15,us7000s09b,2026-02-25 17:17:01.900,4.9,"65 km E of Nichinan, Japan",31.6248,132.0540,10.000,None,False,369
16,us7000s3ge,2026-02-25 21:52:38.345,4.1,"66 km E of Onagawa Chō, Japan",38.3879,142.2024,48.298,None,False,259
17,us7000s15b,2026-03-01 00:35:07.786,4.4,"11 km SE of Kushima, Japan",31.4169,131.3253,56.324,None,False,298
18,us7000s17q,2026-03-01 09:00:08.119,5.5,"21 km SW of Ibusuki, Japan",31.1153,130.4767,127.494,green,False,466
19,us7000s19z,2026-03-01 18:38:48.537,4.6,"98 km ENE of Noda, Japan",40.4463,142.8877,42.921,None,False,326
20,us6000sg2l,2026-03-01 20:18:17.799,4.0,"90 km ENE of Kuji, Japan",40.5370,142.7286,44.076,None,False,246
21,us7000s1vd,2026-03-04 00:48:42.061,4.7,"123 km E of Miyako, Japan",39.7309,143.3790,35.000,None,False,340
22,us7000s2mt,2026-03-06 20:31:51.630,4.8,"64 km ESE of Ōfunato, Japan",38.8143,142.3854,49.239,None,False,354
23,us7000s2z4,2026-03-08 13:08:37.639,5.4,"109 km E of Yamada, Japan",39.3324,143.2138,35.000,green,False,449
24,us7000s2z5,2026-03-08 13:17:08.288,5.7,"110 km E of Yamada, Japan",39.4377,143.2346,16.000,green,False,500
25,us6000sh6h,2026-03-09 00:38:23.824,4.1,"209 km E of Yamada, Japan",39.2493,144.3608,10.000,None,False,259
26,us7000s341,2026-03-09 07:38:59.860,4.9,"Izu Islands, Japan region",30.8003,142.7862,10.000,None,False,369
27,us7000s356,2026-03-09 11:59:31.202,4.1,"5 km SSE of Maizuru, Japan",35.4041,135.3463,364.465,None,False,259
28,us7000s36m,2026-03-09 15:45:43.620,5.9,"19 km NE of Otobe, Japan",42.0868,140.3092,144.000,green,False,536
29,us7000s38u,2026-03-09 21:06:03.583,4.7,"186 km E of Noda, Japan",40.3803,143.9818,10.000,None,False,340
30,us7000s3c4,2026-03-10 06:28:05.052,4.6,"3 km S of Namie, Japan",37.4489,140.9955,69.630,None,False,326
31,us7000s3i8,2026-03-10 22:38:36.605,4.7,"128 km NE of Kuji, Japan",40.9349,142.9239,37.790,None,False,340
32,us7000s3kv,2026-03-11 08:04:34.304,4.3,"277 km SSE of Shimoda, Japan",32.3551,140.0643,127.881,None,False,284
33,us6000sfve,2026-03-12 17:41:22.999,4.1,"9 km SE of Maizuru, Japan",35.3832,135.4012,368.141,None,False,259
34,us6000sg57,2026-03-13 19:55:23.213,5.0,"116 km E of Yamada, Japan",39.3857,143.2972,25.896,None,False,385
35,us6000sgag,2026-03-14 10:19:12.478,4.0,"250 km NNE of Ama, Japan",38.2275,134.0262,419.505,None,False,246
36,us6000sge9,2026-03-15 04:48:44.649,4.3,"134 km E of Tomioka, Japan",37.3728,142.5299,38.742,None,False,284
37,us6000sgeb,2026-03-15 05:06:06.727,4.8,"1 km SW of Kiryū, Japan",36.3919,139.3214,94.896,None,False,357
38,us6000sggw,2026-03-15 16:32:41.643,4.8,"139 km SSE of Honchō, Japan",40.9048,143.3074,37.859,None,False,354
39,us6000sghb,2026-03-15 18:39:12.226,4.7,"30 km SE of Nichinan, Japan",31.4194,131.6063,32.903,None,False,340
40,us6000sghd,2026-03-15 18:56:54.368,4.9,"84 km SSW of Honchō, Japan",41.4045,142.6105,42.986,None,False,370
41,us6000sght,2026-03-15 20:25:17.295,4.3,"27 km NW of Yawatahama, Japan",33.6084,132.1964,66.404,None,False,284
42,us6000sgkn,2026-03-16 11:37:49.386,4.6,"37 km SE of Itō, Japan",34.7732,139.4133,121.973,None,False,326
43,us6000sh1g,2026-03-17 21:13:32.230,4.5,"80 km S of Kushiro, Japan",42.2522,144.3656,35.000,None,False,312
44,us6000sh22,2026-03-17 23:39:22.117,4.3,"Izu Islands, Japan region",30.3452,137.4131,503.225,None,False,284
45,us6000sh54,2026-03-18 10:08:43.719,4.8,"Izu Islands, Japan region",32.4671,141.7638,10.000,None,False,355
46,us6000sh9j,2026-03-18 21:23:02.008,4.7,"52 km NE of Misawa, Japan",40.9524,141.9080,64.376,None,False,340

In [7]:
clean_df['date'] = clean_df['time'].dt.date

# 1. Количество событий по дням (cnt_events)
daily_events = clean_df.groupby('date').agg(
    cnt_events=('id', 'count')
).reset_index()
print("\n1. Количество событий по дням:")
print(daily_events.head())

# 2. Статистика по магнитудам (максимальная, средняя, минимальная) по дням
daily_mag_stats = clean_df.groupby('date').agg(
    max_mag_day=('mag', 'max'),
    avg_mag=('mag', 'mean'),
    min_mag_day=('mag', 'min')
).reset_index()
print("\n2. Статистика по магнитудам по дням:")
print(daily_mag_stats.head())

# 3. Топ-10 событий по магнитуде с местом и глубиной
top10 = clean_df.nlargest(10, 'mag')[['mag', 'place', 'depth_km']]
print("\n3. Топ-10 событий по магнитуде:")
print(top10)

# 4. Доля глубоких событий depth_km > 70
deep_ratio = (clean_df['depth_km'] > 70).mean() * 100
print(f"\n4. Доля глубоких событий (depth_km > 70): {deep_ratio:.2f}%")

# ========== ВЫВОД ==========
print("\n=== Информация о данных ===")
print("head():")
display(clean_df.head())
print(f"\nshape: {clean_df.shape}")
print(f"\ndtypes:\n{clean_df.dtypes}")
print(f"\nТри KPI:")
print(f"- Всего событий: {len(clean_df)}")
print(f"- Максимальная магнитуда: {clean_df['mag'].max():.2f}")
print(f"- Средняя магнитуда: {clean_df['mag'].mean():.2f}")
print(f"- Минимальная магнитуда: {clean_df['mag'].min():.2f}")
print(f"- Доля глубоких событий: {deep_ratio:.2f}%")

# ========== СОХРАНЕНИЕ ВИТРИНЫ ==========
# Создание витрины с ежедневной гранулярностью
mart = daily_events.merge(daily_mag_stats, on='date', how='left')
mart['deep_events_percent'] = deep_ratio
mart['total_events'] = len(clean_df)
mart['max_magnitude_overall'] = clean_df['mag'].max()
mart['region_id'] = 'JP_HON'
mart['region_name'] = 'Япония (Хонсю)'

# Сохранение витрины
mart.to_csv(f"../data/mart/variant_16/mart_daily_{file_name}.csv", index=False, encoding='utf-8')
print(f"\n✓ Витрина сохранена: ../data/mart/variant_16/mart_daily_{file_name}.csv")
print(f"  Количество дней: {len(mart)}")
print(f"\nСтруктура витрины:")
print(mart.head())

1. Количество событий по дням:
         date  cnt_events
0  2026-02-18           1
1  2026-02-19           1
2  2026-02-20           3
3  2026-02-21           1
4  2026-02-23           4

2. Статистика по магнитудам по дням:
         date  max_mag_day   avg_mag  min_mag_day
0  2026-02-18          4.6  4.600000          4.6
1  2026-02-19          4.4  4.400000          4.4
2  2026-02-20          5.3  4.666667          4.2
3  2026-02-21          4.3  4.300000          4.3
4  2026-02-23          4.8  4.525000          4.2

3. Топ-10 событий по магнитуде:
    mag                       place  depth_km
28  5.9    19 km NE of Otobe, Japan   144.000
24  5.7   110 km E of Yamada, Japan    16.000
18  5.5  21 km SW of Ibusuki, Japan   127.494
23  5.4   109 km E of Yamada, Japan    35.000
3   5.3   71 km ENE of Mutsu, Japan    54.152
13  5.2    96 km S of Sukumo, Japan    17.334
34  5.0   116 km E of Yamada, Japan    25.896
15  4.9  65 km E of Nichinan, Japan    10.000
26  4.9   Izu Islands, Japan region    10.000
40  4.9  84 km SSW of Honchō, Japan    42.986

4. Доля глубоких событий (depth_km > 70): 23.40%

=== Информация о данных ===
head():

,id,time,mag,place,latitude,longitude,depth_km,alert,tsunami,sig,date
0,us6000sa20,2026-02-18 22:40:28.752,4.6,"80 km E of Tomioka, Japan",37.3977,141.9228,43.546,None,False,326,2026-02-18
1,us6000sa5d,2026-02-19 08:24:30.319,4.4,"11 km SW of Katsuura, Japan",35.0735,140.2253,10.000,None,False,298,2026-02-19
2,us6000sadg,2026-02-20 10:39:18.090,4.5,"129 km ESE of Iwaki, Japan",36.6758,142.2563,10.000,None,False,312,2026-02-20
3,us6000sae0,2026-02-20 14:16:30.267,5.3,"71 km ENE of Mutsu, Japan",41.5427,141.9999,54.152,None,False,432,2026-02-20
4,us6000sai0,2026-02-20 18:59:32.395,4.2,"88 km SSE of Onagawa Chō, Japan",37.7788,142.0091,51.363,None,False,271,2026-02-20

shape: (47, 11)

dtypes:
id                      str
time         datetime64[ms]
mag                 float64
place                   str
latitude            float64
longitude           float64
depth_km            float64
alert                   str
tsunami                bool
sig                   int64
date                 object
dtype: object

Три KPI:
- Всего событий: 47
- Максимальная магнитуда: 5.90
- Средняя магнитуда: 4.63
- Минимальная магнитуда: 4.00
- Доля глубоких событий: 23.40%

✓ Витрина сохранена: ../data/mart/variant_16/mart_daily_2026-03-20_11-46-40.csv
  Количество дней: 21

Структура витрины:
         date  cnt_events  max_mag_day   avg_mag  min_mag_day  \
0  2026-02-18           1          4.6  4.600000          4.6
1  2026-02-19           1          4.4  4.400000          4.4
2  2026-02-20           3          5.3  4.666667          4.2
3  2026-02-21           1          4.3  4.300000          4.3
4  2026-02-23           4          4.8  4.525000          4.2

   deep_events_percent  total_events  max_magnitude_overall region_id  \
0            23.404255            47                    5.9    JP_HON
1            23.404255            47                    5.9    JP_HON
2            23.404255            47                    5.9    JP_HON
3            23.404255            47                    5.9    JP_HON
4            23.404255            47                    5.9    JP_HON

      region_name
0  Япония (Хонсю)
1  Япония (Хонсю)
2  Япония (Хонсю)
3  Япония (Хонсю)
4  Япония (Хонсю)